codigos = {'00': '00 - Crédito ou Débito Efetivado > Este código indica que o pagamento foi confirmado \\',
           '01': '01 - Insuficiência de Fundos - Débito Não Efetuado \\',
           '02': '02 - Crédito ou Débito Cancelado pelo Pagador/Credor \\',
           '03': '03 - Débito Autorizado pela Agência - Efetuado \\',
           'AA': 'AA - Controle Inválido \\',
           'AB': 'AB - Tipo de Operação Inválido \\',
           'AC': 'AC - Tipo de Serviço Inválido \\',
           'AD': 'AD - Forma de Lançamento Inválida \\',
           'AE': 'AE - Tipo/Número de Inscrição Inválido \\',
           'AF': 'AF - Código de Convênio Inválido \\',
           'AG': 'AG - Agência/Conta Corrente/DV Inválido \\',
           'AH': 'AH - Nº Seqüencial do Registro no Lote Inválido \\',
           'AI': 'AI - Código de Segmento de Detalhe Inválido \\',
           'AJ': 'AJ - Tipo de Movimento Inválido \\',
           'AK': 'AK - Código da Câmara de Compensação do Banco Favorecido/Depositário Inválido \\',
           'AL': 'AL - Código do Banco Favorecido ou Depositário Inválido \\',
           'AM': 'AM - Agência Mantenedora da Conta Corrente do Favorecido Inválida \\',
           'AN': 'AN - Conta Corrente/DV do Favorecido Inválido \\',
           'AO': 'AO - Nome do Favorecido Não Informado \\',
           'AP': 'AP - Data Lançamento Inválido \\',
           'AQ': 'AQ - Tipo/Quantidade da Moeda Inválido \\',
           'AR': 'AR - Valor do Lançamento Inválido \\',
           'AS': 'AS - Aviso ao Favorecido - Identificação Inválida \\',
           'AT': 'AT - Tipo/Número de Inscrição do Favorecido Inválido \\',
           'AU': 'AU - Logradouro do Favorecido Não Informado \\',
           'AV': 'AV - Nº do Local do Favorecido Não Informado \\',
           'AW': 'AW - Cidade do Favorecido Não Informada \\',
           'AX': 'AX - CEP/Complemento do Favorecido Inválido \\',
           'AY': 'AY - Sigla do Estado do Favorecido Inválida \\',
           'AZ': 'AZ - Código/Nome do Banco Depositário Inválido \\',
           'BA': 'BA - Código/Nome da Agência Depositária Não Informado \\',
           'BB': 'BB - Seu Número Inválido \\',
           'BC': 'BC - Nosso Número Inválido \\',
           'BD': 'BD - Inclusão Efetuada com Sucesso \\',
           'BE': 'BE - Alteração Efetuada com Sucesso \\',
           'BF': 'BF - Exclusão Efetuada com Sucesso \\',
           'BG': 'BG - Agência/Conta Impedida Legalmente \\',
           'BH': 'BH - Empresa não pagou salário \\',
           'BI': 'BI - Falecimento do mutuário \\',
           'BJ': 'BJ - Empresa não enviou remessa do mutuário \\',
           'BK': 'BK - Empresa não enviou remessa no vencimento \\',
           'BL': 'BL - Valor da parcela inválida \\',
           'BM': 'BM - Identificação do contrato inválida \\',
           'BN': 'BN - Operação de Consignação Incluída com Sucesso \\',
           'BO': 'BO - Operação de Consignação Alterada com Sucesso \\',
           'BP': 'BP - Operação de Consignação Excluída com Sucesso \\',
           'BQ': 'BQ - Operação de Consignação Liquidada com Sucesso \\',
           'CA': 'CA - Código de Barras - Código do Banco Inválido \\',
           'CB': 'CB - Código de Barras - Código da Moeda Inválido \\',
           'CC': 'CC - Código de Barras - Dígito Verificador Geral Inválido \\',
           'CD': 'CD - Código de Barras - Valor do Título Inválido \\',
           'CE': 'CE - Código de Barras - Campo Livre Inválido \\',
           'CF': 'CF - Valor do Documento Inválido \\',
           'CG': 'CG - Valor do Abatimento Inválido \\',
           'CH': 'CH - Valor do Desconto Inválido \\',
           'CI': 'CI - Valor de Mora Inválido \\',
           'CJ': 'CJ - Valor da Multa Inválido \\',
           'CK': 'CK - Valor do IR Inválido \\',
           'CL': 'Cl - Valor do ISS Inválido \\',
           'CM': 'CM - Valor do IOF Inválido \\',
           'CN': 'CN - Valor de Outras Deduções Inválido \\',
           'CO': 'CO - Valor de Outros Acréscimos Inválido \\',
           'CP': 'CP - Valor do INSS Inválido \\',
           'HA': 'HA - Lote Não Aceito \\',
           'HB': 'HB - Inscrição da Empresa Inválida para o Contrato \\',
           'HC': 'HC - Convênio com a Empresa Inexistente/Inválido para o Contrato \\',
           'HD': 'HD - Agência/Conta Corrente da Empresa Inexistente/Inválido para o Contrato \\',
           'HE': 'HE - Tipo de Serviço Inválido para o Contrato \\',
           'HF': 'HF - Conta Corrente da Empresa com Saldo Insuficiente \\',
           'HG': 'HG - Lote de Serviço Fora de Seqüência \\',
           'HH': 'HH - Lote de Serviço Inválido \\',
           'HI': 'HI - Arquivo não aceito \\',
           'HJ': 'HJ - Tipo de Registro Inválido \\',
           'HK': 'HK - Código Remessa / Retorno Inválido \\',
           'HL': 'HL - Versão de layout inválida \\',
           'HM': 'HM - Mutuário não identificado \\',
           'HN': 'HN - Tipo do beneficio não permite empréstimo \\',
           'HO': 'HO - Beneficio cessado/suspenso \\',
           'HP': 'HP - Beneficio possui representante legal \\',
           'HQ': 'HQ - Beneficio é do tipo PA(Pensão alimentícia) \\',
           'HR': 'HR - Quantidade de contratos permitida excedida \\',
           'HS': 'HS - Beneficio não pertence ao Banco informado \\',
           'HT': 'HT - Início do desconto informado já ultrapassado \\',
           'HU': 'Hu - Número da parcela inválida \\',
           'HV': 'HV - Quantidade de parcela inválida \\',
           'HW': 'HW - Margem consignável excedida para o mutuário dentro do prazo do contrato \\',
           'HX': 'HX - Empréstimo já cadastrado \\',
           'HY': 'HY - Empréstimo inexistente \\',
           'HZ': 'HZ - Empréstimo já encerrado \\',
           'H1': 'H1 - Arquivo sem trailer \\',
           'H2': 'H2 - Mutuário sem crédito na competência \\',
           'H3': 'H3 - Não descontado - outros motivos \\',
           'H4': 'H4 - Retorno de Crédito não pago \\',
           'H5': 'H5 - Cancelamento de empréstimo retroativo \\',
           'H6': 'H6 - Outros Motivos de Glosa \\',
           'H7': 'H7 - Margem consignável excedida para o mutuário acima do prazo do contrato \\',
           'H8': 'H8 - Mutuário desligado do empregador \\',
           'H9': 'H9 - Mutuário afastado por licença \\',
           'TA': 'TA - Lote Não Aceito - Totais do Lote com Diferença \\',
           'YA': 'YA - Título Não Encontrado \\',
           'YB': 'YB - Identificador Registro Opcional Inválido \\',
           'YC': 'YC - Código Padrão Inválido \\',
           'YD': 'YD - Código de Ocorrência Inválido \\',
           'YE': 'YE - Complemento de Ocorrência Inválido \\',
           'YF': 'YF - Alegação já Informada \\',
           'ZA': 'ZA - Agência / Conta do Favorecido Substituída \\', }
